---
name: "Channelz"
guid: "84978100-fe55-454e-b566-44b7f4e8a400"
version: "1.0.4.0"
targetAbi: "10.11.4.0"
framework: "net9.0"
overview: "Live TV using your own libraries"
description: >
  Live TV Channels in Jellyfin from your own library allowing direct play
category: "livetv"
owner: "scotech"
artifacts:
- "Jellyfin.Plugins.Channelz.dll"
changelog: >
  changelog
imageUrl: "https://raw.githubusercontent.com/scotech/jellyfin-plugin-channelz/refs/heads/master/images/icon.png"
